### ISSUE TITLE
Windows MSVC build looking for Wasmer dynamic library

### ISSUE THREAD

**Issue by fire** [ashtonmeuser/godot-wasm#29]
When I download from a github action godot engine fails to execute.

Expected to use a static library.

A .dll side by side is not so good.

**Comment by ashtonmeuser** [comment]
A little more context here might help. I'll add an issue template at some point to prompt for some more details.

Godot version: https://github.com/V-Sekai/godot/commit/dcd050b7109c770d8b5e2a5520ac91202d071f53
Godot Wasm version: https://github.com/V-Sekai/godot-wasm/commit/74e52787dc8f92cf0672b5b3760f86324085f345
OS: Microsoft Windows Server 2022 10.0.20348
Build target platform: Windows

@fire Is the compiled editor looking for the Wasmer DLL or the Godot Wasm DLL? Can you add the actual error?

**Comment by fire** [comment]
The compiler editor is looking for a wasmer.dll. If you place it beside the executable it should work.

I prefer to somehow have a static library so instead of three binaries [godot.exe, wasmer.dll, game.pck] it'll be two and one binary if we embed the pck.

**Comment by ashtonmeuser** [comment]
Makes total sense. Wonder if changing the Wasmer library suffix to `.lib` rather than `.lib.dll` would do the trick.

**Comment by fire** [comment]
Does https://github.com/wasmerio/wasmer/releases/download/v3.3.0/wasmer-windows-gnu64.tar.gz provide static libs?

I don't see evidence of this.

**Comment by ashtonmeuser** [comment]
That's a separate issue, no? Your build is using MSVC which downloads https://github.com/wasmerio/wasmer/releases/download/v3.1.1/wasmer-windows-amd64.tar.gz which contains static libs.

**Comment by fire** [comment]
Ah mistaken. Let me check

**Comment by fire** [comment]
![image](https://user-images.githubusercontent.com/32321/236605796-046c7e1c-6017-4d91-b66d-c6963d09b533.png)

Not sure how we got here.

**Comment by ashtonmeuser** [comment]
Hey it's one step closer! At least the engine compiles. I've dusted off the ol' Windows box so will have a better idea of what's happening. In the meantime, is it worth trying to load with a DLL present? Might tell us if there are any further issues.

**Comment by fire** [comment]
Testing

```diff
> git diff
diff --git a/modules/wasm/SCsub b/modules/wasm/SCsub
index 0d1906da742..09e00993b9a 100644
--- a/modules/wasm/SCsub
+++ b/modules/wasm/SCsub
@@ -16,7 +16,7 @@ elif env["platform"] in ["osx", "macos"]:
     module_env.Append(CXXFLAGS=["-std=c++17"])
     env.Append(LINKFLAGS=["-framework", "Security"])
 elif env["platform"] == "windows":
-    env["LIBWASMERSUFFIX"] = ".dll.lib"
+    env["LIBWASMERSUFFIX"] = ".lib"
     if env.get("use_mingw"):
         env["LIBWASMERSUFFIX"] = ".a"
         env.Append(LIBS=["userenv"])
```

**Comment by fire** [comment]
I'll kludge it by disabling the wasmer module compiling for msvc but keeping mingw support while I wait.

**Comment by ashtonmeuser** [comment]
Looks like when Godot Wasm was swapped to use static libs (https://github.com/ashtonmeuser/godot-wasm/commit/f8a84cfb9ae02ac86dc670e3921d20c729e96a00), no change was made to MSVC compilation. Same problem exists for all MSVC builds. See below for dependencies of the DLL created for Godot 3.x GDNative addon.

![Screenshot 2023-05-06 172015](https://user-images.githubusercontent.com/7253863/236638564-c4072bdb-6027-48ce-9506-491858504c01.png)

**Comment by ashtonmeuser** [comment]
I've got a fix for this but haven't had much of a chance to implement today. Will update shortly.

**Comment by fire** [comment]
I saw an update!

**Comment by ashtonmeuser** [comment]
Should be fixed with https://github.com/ashtonmeuser/godot-wasm/commit/29356da3fbbffe2d33f7210c7742d699178a867d (Godot 3.x) and https://github.com/ashtonmeuser/godot-wasm/commit/2999e89a5f65e91625ad7a728c318b577439b98b (Godot 4.x).

The root cause was an issue with statically linking [Wasmer](https://github.com/wasmerio/wasmer) which in turn is caused by an issue with the [Wasm C API](https://github.com/WebAssembly/wasm-c-api). I've fixed it with a hotpatch and will open an issue upstream.

### Explanation

I didn't fully understand how C libraries in Windows worked. TL;DR: A `.lib` file can be either a static library or an import library. A DLL isn't a perfect metaphor for a *nix dynamic library as it hides it's symbols. It requires an import library (also `.lib` extension) to expose symbols. Wasmer provides both static and dynamic libraries in their Windows release artifact and differentiates the two with `.lib` and `.dll.lib`, respectively.

The Wasm C API (and thus Wasmer) assume all Windows implementations use the DLL and call `__declspec(dllimport)` if the `_WIN32` define is present e.g. Windows or MinGW. Using the static `.lib` with `__declspec(dllimport)` was declaring but not defining symbols (citation needed; I'm out of my depth here).

Very related to https://github.com/ashtonmeuser/godot-wasm/issues/26. In fact, we nearly accidentally solved this. The other piece of information that lead to the solve is here: https://github.com/wasmerio/wasmer/issues/3298. Interestingly, the exact bug in Wasmer/Wasm C API was pointed out by a user there but I dismissed it in favour of dynamic linking. Didn't recall this when moving to static linking in https://github.com/ashtonmeuser/godot-wasm/commit/f8a84cfb9ae02ac86dc670e3921d20c729e96a00.

**Comment by ashtonmeuser** [comment]
@fire I'll keep an eye on [your build](https://github.com/V-Sekai/godot/actions/runs/4905044686). Let me know if we're good to close this.

**Comment by fire** [comment]
I am having trouble apply the patch on windows 11 on the windows command prompt with msvc.

Also, `LINK : fatal error LNK1181: cannot open input file 'userenv.lib.windows.editor.double.x86_64.lib'`

**Comment by fire** [comment]
The build failed on Github actions.

**Comment by ashtonmeuser** [comment]
[Failed job](https://github.com/V-Sekai/godot/actions/runs/4905044686/jobs/8758584049)

```
link @C:\Users\RUNNER~1\AppData\Local\Temp\tmpi87egrjz.lnk
   Creating library bin\godot.windows.template_release.x86_64.lib and object bin\godot.windows.template_release.x86_64.exp
wasmer.lib(std-2e5a4fde2066d4f2.std.db95cb0e-cgu.0.rcgu.o) : error LNK2019: unresolved external symbol __imp_GetUserProfileDirectoryW referenced in function _ZN3std3env8home_dir17hca690f225b519101E
bin\godot.windows.template_release.x86_64.exe : fatal error LNK1120: 1 unresolved externals
scons: *** [bin\godot.windows.template_release.x86_64.exe] Error 1120
scons: building terminated because of errors.
[Time elapsed: 00:51:36.272]
Error: Process completed with exit code 2.
```

This doesn't feel related to Godot Wasm but I could be wrong. Lemme check on my end. I should really set up a minimal module build workflow for this repo.

**Comment by fire** [comment]
`__imp_GetUserProfileDirectoryW` is https://learn.microsoft.com/en-us/windows/win32/api/userenv/nf-userenv-getuserprofiledirectoryw

aka "userenv"

**Comment by ashtonmeuser** [comment]
Nice find! Guess we can take out the MinGW check but that might put us back to exactly https://github.com/ashtonmeuser/godot-wasm/issues/27.

**Comment by fire** [comment]
Fixed.
