### ISSUE TITLE
Windows msvc scons build sometimes doesn't update the wasmer download

### ISSUE THREAD

**Issue by fire** [ashtonmeuser/godot-wasm#35]
Sometimes you need to delete the wasmer folder.

**Comment by ashtonmeuser** [comment]
This was behaviour is intentional because downloading Wasmer each time the addon/engine is built would be inefficient as most of the time, you'll be redownloading the same Wasmer version. If the _wasmer_ directory exists, the download is skipped. This behaviour has always been overridable when building a GDNative/GDExtension addon via a `download_wasmer=yes` argument. Relatedly, a specific version of Wasmer can be specified via `wasmer_version=vX.Y.Z`.

Anyway, I implemented these same options when building as a Godot module. Commits https://github.com/ashtonmeuser/godot-wasm/commit/6db146b1f2b03457937ac9bd209a4dfb17dc931c (Godot 3.x) and https://github.com/ashtonmeuser/godot-wasm/commit/f2b1cc3bb2dc254d21f62c4228be8dc1cd8bbaa0 (Godot 4.x).
